import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useCallback, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { Card, ChoicePills, EmptyState, LoadingState, PageTitle, Screen, SectionLabel, StatusPill, formatDateTime } from '@/components/driver-ui';
import { AppColors } from '@/constants/app-theme';
import { useDriverApp } from '@/context/driver-app-context';
import { getIssueReports } from '@/db/service';
import type { IssueReport } from '@/types';

const typeFilters = ['All', 'Traffic congestion', 'Accident', 'Bus breakdown', 'Other issue'] as const; const syncFilters = ['All', 'pending', 'synced'] as const;
export default function HistoryScreen() { const db = useSQLiteContext(); const { profile } = useDriverApp(); const [type, setType] = useState<(typeof typeFilters)[number]>('All'); const [sync, setSync] = useState<(typeof syncFilters)[number]>('All'); const [items, setItems] = useState<IssueReport[] | null>(null); const load = useCallback(async () => { if (profile) setItems(await getIssueReports(db, profile.id, type, sync)); }, [db, profile, sync, type]); useFocusEffect(useCallback(() => { void load(); }, [load])); return <Screen><PageTitle title="Report history" subtitle="Issues saved from your driver account" /><SectionLabel>Issue type</SectionLabel><ChoicePills values={typeFilters} selected={type} onChange={setType} /><SectionLabel>Sync status</SectionLabel><ChoicePills values={syncFilters} selected={sync} onChange={setSync} color="green" />{items === null ? <LoadingState label="Loading reports..." /> : items.length === 0 ? <EmptyState title="No matching reports" message="Try a different filter or submit a new report." /> : <View style={styles.list}>{items.map((item) => <Card key={item.id} style={styles.report}><View style={styles.copy}><View style={styles.row}><Text style={styles.title}>{item.issue_type}</Text>{item.is_emergency === 1 && <StatusPill label="SOS" tone="red" />}</View><Text style={styles.detail}>{formatDateTime(item.reported_at)}</Text><Text style={styles.detail}>{item.latitude !== null ? `${item.latitude.toFixed(4)}, ${item.longitude?.toFixed(4)}` : 'Location unavailable'}</Text>{item.description ? <Text style={styles.description}>{item.description}</Text> : null}</View><View style={styles.badges}><StatusPill label={item.severity} tone={item.severity === 'Critical' ? 'red' : item.severity === 'High' ? 'orange' : 'blue'} /><StatusPill label={item.sync_status} tone={item.sync_status === 'synced' ? 'green' : 'orange'} /></View></Card>)}</View>}</Screen>; }
const styles = StyleSheet.create({ list: { gap: 10 }, report: { flexDirection: 'row', gap: 8, justifyContent: 'space-between' }, copy: { flex: 1, gap: 5 }, row: { flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' }, title: { color: AppColors.navy, fontSize: 15, fontWeight: '800', flexShrink: 1 }, detail: { color: AppColors.muted, fontSize: 12 }, description: { color: AppColors.text, fontSize: 12, lineHeight: 17, marginTop: 2 }, badges: { alignItems: 'flex-end', gap: 6 }, });
