import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { useCallback, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';

import { AppButton, Card, ChoicePills, EmptyState, Field, LoadingState, PageTitle, Screen, SectionLabel, StatusPill, formatDateTime } from '@/components/driver-ui';
import { AppColors } from '@/constants/app-theme';
import { useDriverApp } from '@/context/driver-app-context';
import { getInspectionHistory, markInspectionSynced, saveInspection } from '@/db/service';
import { syncInspection } from '@/services/transport-api';
import type { VehicleInspection } from '@/types';

const conditionValues = ['Good', 'Fair', 'Poor'] as const;
const lightValues = ['Good', 'Faulty'] as const;

export default function InspectionScreen() {
  const db = useSQLiteContext(); const { profile, refreshProfile } = useDriverApp();
  const [fuel, setFuel] = useState(profile ? String(profile.fuel_or_battery_level) : ''); const [temperature, setTemperature] = useState('');
  const [tyres, setTyres] = useState<(typeof conditionValues)[number]>('Good'); const [brakes, setBrakes] = useState<(typeof conditionValues)[number]>('Good'); const [lights, setLights] = useState<(typeof lightValues)[number]>('Good'); const [fault, setFault] = useState(''); const [history, setHistory] = useState<VehicleInspection[] | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (profile) setHistory(await getInspectionHistory(db, profile.id)); }, [db, profile]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (!profile) return <Screen scroll={false}><LoadingState label="Loading inspection..." /></Screen>;
  const driver = profile;
  const healthTone = driver.health_status === 'Good' ? 'green' : driver.health_status === 'Critical' ? 'red' : 'orange';
  async function submit() { const level = fuel.trim() === '' ? null : Number(fuel); const temp = temperature.trim() === '' ? null : Number(temperature); if ((level !== null && (Number.isNaN(level) || level < 0 || level > 100)) || (temp !== null && Number.isNaN(temp))) { Alert.alert('Check values', 'Fuel/battery must be 0 to 100 and temperature must be a number.'); return; } setSaving(true); try { const saved = await saveInspection(db, { busId: driver.assigned_bus_id, driverId: driver.id, fuelLevel: level, engineTemperature: temp, tyreCondition: tyres, brakeCondition: brakes, lightsCondition: lights, faultDescription: fault }); const synced = await syncInspection({ busId: driver.bus_number, driverId: driver.driver_code, fuelBatteryLevel: level, engineTemperature: temp, tyreCondition: tyres, brakeCondition: brakes, lightsCondition: lights, faultDescription: fault }); if (synced) await markInspectionSynced(db, saved.inspectionId); await refreshProfile(); await load(); Alert.alert(saved.health === 'Critical' ? 'Maintenance alert' : synced ? 'Inspection sent' : 'Inspection saved', saved.health === 'Critical' ? 'A critical vehicle item was reported. Please contact maintenance.' : synced ? 'The government dashboard received the inspection.' : 'Inspection is saved locally and will sync when the server is available.'); setFault(''); } catch { Alert.alert('Could not save inspection', 'Please try again.'); } finally { setSaving(false); } }
  return <Screen><PageTitle title="Vehicle inspection" subtitle={`${driver.bus_number} · Check before or during a shift`} /><Card style={styles.health}><View><Text style={styles.healthTitle}>Current vehicle health</Text><Text style={styles.healthText}>{driver.fuel_or_battery_level}% {driver.fuel_type}</Text></View><StatusPill label={driver.health_status} tone={healthTone} /></Card><Card style={styles.form}><Field label={`${driver.fuel_type} level (%)`} value={fuel} onChangeText={setFuel} keyboardType="numeric" placeholder="0-100" /><Field label="Engine temperature (°C)" value={temperature} onChangeText={setTemperature} keyboardType="decimal-pad" placeholder="Optional" /><SectionLabel>Tyre condition</SectionLabel><ChoicePills values={conditionValues} selected={tyres} onChange={setTyres} color={tyres === 'Poor' ? 'red' : 'green'} /><SectionLabel>Brake condition</SectionLabel><ChoicePills values={conditionValues} selected={brakes} onChange={setBrakes} color={brakes === 'Poor' ? 'red' : 'green'} /><SectionLabel>Lights condition</SectionLabel><ChoicePills values={lightValues} selected={lights} onChange={setLights} color={lights === 'Faulty' ? 'red' : 'green'} /><Field label="Fault description (optional)" value={fault} onChangeText={setFault} placeholder="Describe a vehicle fault" multiline /><AppButton label="Submit inspection" onPress={submit} loading={saving} /></Card><SectionLabel>Previous inspections</SectionLabel>{history === null ? <LoadingState label="Loading history..." /> : history.length === 0 ? <EmptyState title="No inspections yet" message="Your inspection records will appear here." /> : history.map((item) => <Card key={item.id} style={styles.history}><View><Text style={styles.historyTitle}>{item.health_status}</Text><Text style={styles.historyText}>{formatDateTime(item.inspected_at)} · {item.fuel_or_battery_level ?? '—'}%</Text></View><StatusPill label={item.sync_status} tone={item.sync_status === 'synced' ? 'green' : 'orange'} /></Card>)}</Screen>;
}
const styles = StyleSheet.create({ health: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, healthTitle: { color: AppColors.navy, fontSize: 16, fontWeight: '800' }, healthText: { color: AppColors.muted, fontSize: 13, marginTop: 5 }, form: { gap: 13 }, history: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, historyTitle: { color: AppColors.navy, fontSize: 15, fontWeight: '800' }, historyText: { color: AppColors.muted, fontSize: 12, marginTop: 4 }, });
