import { router } from 'expo-router';
import { Alert, StyleSheet, Text, View } from 'react-native';

import { AppButton, Card, LoadingState, PageTitle, Screen, SectionLabel, StatusPill } from '@/components/driver-ui';
import { AppColors } from '@/constants/app-theme';
import { useDriverApp } from '@/context/driver-app-context';

export default function ProfileScreen() {
  const { profile, logout } = useDriverApp();
  if (!profile) return <Screen scroll={false}><LoadingState label="Loading profile..." /></Screen>;
  function confirmLogout() { Alert.alert('Log out?', 'You can log in again with the demo details.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log out', style: 'destructive', onPress: () => { void logout().then(() => router.replace('/login')); } }]); }
  return <Screen><PageTitle title="Profile & settings" subtitle="Your driver assignment" /><Card style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{profile.name.slice(0, 1)}</Text></View><View><Text style={styles.name}>{profile.name}</Text><Text style={styles.code}>{profile.driver_code}</Text></View></Card><SectionLabel>Assigned bus</SectionLabel><Card style={styles.row}><View><Text style={styles.value}>{profile.bus_number}</Text><Text style={styles.detail}>{profile.vehicle_type} · {profile.fuel_type}</Text></View><StatusPill label={profile.health_status} tone={profile.health_status === 'Good' ? 'green' : profile.health_status === 'Critical' ? 'red' : 'orange'} /></Card><SectionLabel>Assigned route</SectionLabel><Card><Text style={styles.value}>Route {profile.route_number}</Text><Text style={styles.detail}>{profile.route_name}</Text><Text style={styles.stops}>{profile.start_stop} → {profile.end_stop}</Text></Card><Card style={styles.privacy}><Text style={styles.privacyTitle}>Privacy note</Text><Text style={styles.privacyText}>This app collects trip and vehicle data only for public transport operations. It does not store passenger identity or private passenger data.</Text></Card><AppButton label="Log out" variant="danger" onPress={confirmLogout} /></Screen>;
}
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', gap: 13 }, avatar: { width: 52, height: 52, borderRadius: 26, backgroundColor: AppColors.green, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: AppColors.white, fontWeight: '900', fontSize: 22 }, name: { color: AppColors.navy, fontWeight: '900', fontSize: 18 }, code: { color: AppColors.muted, fontSize: 13, marginTop: 4 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, value: { color: AppColors.navy, fontWeight: '800', fontSize: 16 }, detail: { color: AppColors.muted, fontSize: 13, marginTop: 5 }, stops: { color: AppColors.text, fontSize: 13, marginTop: 12 }, privacy: { backgroundColor: AppColors.navySoft, borderColor: '#D4E3ED', gap: 5 }, privacyTitle: { color: AppColors.navy, fontWeight: '800' }, privacyText: { color: AppColors.text, fontSize: 13, lineHeight: 19 }, });
